name: Check JIRA Reference in Title

on:
    pull_request:
        branches: [ $default-branch ]
        types: [ opened, edited ]

jobs:
    check-title:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR Title for JIRA Ticket
              run: |
                  if [[ ! "${{ github.event.pull_request.title }}" =~ [A-Z]+-[0-9]+ ]]; then
                    echo "PR title must include a JIRA ticket (e.g., [JIRA-123])."
                    exit 1
                  fi
